# Generated by Django 5.2.7 on 2025-10-25 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_collection_featured_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='given_name',
            new_name='first_name',
        ),
    ]
