# Generated by Django 5.2.7 on 2025-11-21 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaagedItem',
            new_name='TaggedItem',
        ),
    ]
